### ISSUE TITLE
Error running npm start on windows

### ISSUE THREAD

**Issue by jpierson** [knowbody/redux-react-router-example-app#13] opened 2015-10-28 08:37 UTC
Below is an error that I see after running npm start on Windows 10.

> ERROR in ./~/react-tap-event-plugin/src/TapEventPlugin.js
> Module not found: Error: Cannot resolve module 'fbjs/lib/keyOf' in C:\Users\myuser\Source\examples\redux-react-router-example-app\node_modules\react-tap-event-plugin\src
>  @ ./~/react-tap-event-plugin/src/TapEventPlugin.js 29:12-37
> 
> webpack: bundle is now VALID.

Subsequently when trying to navigate to _http://localhost:3000/_ in the browser I'm getting _404_ for _bundle.js_.

**Comment by knowbody** [comment] 2015-10-28 09:20
@jpierson looking into it now, but will need your help as I have no access to the Windows 10 machine :disappointed:

**Comment by knowbody** [comment] 2015-10-28 13:32
@jpierson check it out now, I've done bunch of updates

**Comment by knowbody** [comment] 2015-10-30 17:50
@jpierson check out now, I've done bunch of updates.

**Comment by jpierson** [comment] 2015-10-30 18:16
Trying it out now. 

``` powershell
git pull
npm install
npm start
```

I'm not getting the same error but I'm running into some issues with unmet peer dependencies.

```
UNMET PEER DEPENDENCY react-addons-create-fragment@^0.14.0
├── UNMET PEER DEPENDENCY react-addons-pure-render-mixin@^0.14.0
├── UNMET PEER DEPENDENCY react-addons-transition-group@^0.14.0
├── UNMET PEER DEPENDENCY react-addons-update@^0.14.0
```

```
npm WARN EPEERINVALID material-ui@0.13.1 requires a peer of react-addons-transition-group@^0.14.0 but none was installed.
npm WARN EPEERINVALID material-ui@0.13.1 requires a peer of react-addons-update@^0.14.0 but none was installed.
npm WARN EPEERINVALID material-ui@0.13.1 requires a peer of react-addons-create-fragment@^0.14.0 but none was installed.
npm WARN EPEERINVALID material-ui@0.13.1 requires a peer of react-addons-pure-render-mixin@^0.14.0 but none was installed
```

**Comment by knowbody** [comment] 2015-10-30 18:25
@jpierson those are just warnings from material-ui, I'll fix those warnings in a bit. But does the app work fine for you now?

**Comment by jpierson** [comment] 2015-10-30 18:37
I'm just seeing a blank page when hitting http://localhost:3000. I also I see this in the console.

> Uncaught SyntaxError: Unexpected token <

**Comment by knowbody** [comment] 2015-10-30 19:00
hmm... hard for me to debug as I don't have Windows 10, and it works fine for me. I'll try to debug it somehow.

**Comment by brakmic** [comment] 2015-10-30 19:15
Hi @jpierson,
Hi @knowbody  

The error "Uncaught SyntaxError: Unexpected token <" mostly happens when a _server-side router_ doesn't know how to serve a certain file (for example, because there's no proper path/access rule available) and instead sends the default document (index.html, for example).

Now, because your JavaScript code was expecting some JS and not an HTML document this error appears.

I know nothing about React but because these things happen to me, from time to time, when I forget to update my HapiJS router configs :smile:

**Comment by knowbody** [comment] 2015-10-30 19:17
@brakmic thanks, but I'm not sure that that is the problem here, as it works just fine on my Mac, it seems to not work on Windows 10

**Comment by brakmic** [comment] 2015-10-30 19:19
Ok, I'll download the sources, because I'm running Win10 too.
However, I know nothing about React, so expect me to disappear without notice :smile:

**Comment by brakmic** [comment] 2015-10-30 19:23
removed...misleading error...

**Comment by knowbody** [comment] 2015-10-30 19:24
@brakmic you need to have node.js installed on your machine

**Comment by brakmic** [comment] 2015-10-30 19:24
Sorry, wrong error...will now delete it...

**Comment by brakmic** [comment] 2015-10-30 19:25
I only used react for a few times...know nothing about it....

**Comment by brakmic** [comment] 2015-10-30 19:26
ok...the first "real" error is that it can't find "webpack"...but I do have webpack...as a global module...

**Comment by knowbody** [comment] 2015-10-30 19:26
I might just install Windows 10 on the VM

**Comment by brakmic** [comment] 2015-10-30 19:28
Well, I think, WIndows users should install complex packages always together with the flag **--msvs_version=2013** or **--msvs_version=2015** .... with this flag the build tools from node will know which version of Visual Studio build tools are available on their machines. I always do that.

**Comment by brakmic** [comment] 2015-10-30 19:31
Well, this is the console output...everything works fine

``` shell

> redux-blogapp@0.0.1 start D:\src\js\react\redux-react-router-example-app              
> node server.js                                                                        

Fake API listening at localhost:3010                                                    
Listening at localhost:3000                                                             
webpack built 2564316d7b4a6341eb22 in 26427ms                                           
OPTIONS /post?_start=0&_limit=10 204 4.343 ms - -                                       
OPTIONS /user 204 1.121 ms - -                                                          
GET /post?_start=0&_limit=10 200 52.725 ms - 4164                                       
GET /user 200 64.783 ms - 24459                                                         

```

**Comment by brakmic** [comment] 2015-10-30 19:32
Here's the screenshot:

![output](https://cloud.githubusercontent.com/assets/56779/10856049/513c2cfe-7f45-11e5-8dba-fc7c25ce782c.png)

**Comment by knowbody** [comment] 2015-10-30 19:45
YAY! Thanks @brakmic.

So now what is wrong with @jpierson setup?

**Comment by brakmic** [comment] 2015-10-30 19:46
Well, if you take into account that I never use React and run Windows 10 and have only downloaded your sources and "npm i" + "npm start", then I'd say: everything's OK. :smile: 

But as I've said: I strongly recommend to compile node packages under Windows together with **--msvs_version** flags.

**Comment by knowbody** [comment] 2015-10-30 19:56
@jpierson closing as it doesn't seem like a bug on my side. Please have a look at the advice given by @brakmic.

**Closed as completed by knowbody** 2015-10-30 19:56 UTC

**Comment by jpierson** [comment] 2015-11-03 16:33
I figured that the issue was related to missing dependencies based on the error, perhaps modules that were installed locally that didn't make their way into packages.json. To test this out I installed the missing peer dependencies that were reported in the output from `npm start` and now I'm able to get things working. Note that to install the dependencies I also had to update to React 0.14.2. Below is a snippet of the changes/additions made to the _dependencies_ in packages.json which made this work for me.

``` json
    "react": "^0.14.2",
    "react-addons-create-fragment": "^0.14.2",
    "react-addons-pure-render-mixin": "^0.14.2",
    "react-addons-transition-group": "^0.14.2",
    "react-addons-update": "^0.14.2",
```

**Comment by jpierson** [comment] 2015-11-03 16:47
Just to repeat the test I've reverted all of my local changes using the following commands.

```
git reset --hard
git clean -f
rmdir node_modules
```

Then upon running `npm install` I see the following warnings. 

> npm WARN EPEERINVALID material-ui@0.13.1 requires a peer of react-addons-transition-group@^0.14.0 but none was installed.
> npm WARN EPEERINVALID material-ui@0.13.1 requires a peer of react-addons-update@^0.14.0 but none was installed.
> npm WARN EPEERINVALID material-ui@0.13.1 requires a peer of react-addons-create-fragment@^0.14.0 but none was installed.
> npm WARN EPEERINVALID material-ui@0.13.1 requires a peer of react-addons-pure-render-mixin@^0.14.0 but none was installed.

Running `npm start` I then see the original errors that I reported above. It also appears that the file bundle.js is being served the following content.

``` html
<html>
  <head>
    <title>React Redux Boilerplate</title>
  </head>
  <body style="margin: 0; -webkit-font-smoothing: antialiased;">
    <div id="root"></div>
  </body>
  <script src="./static/bundle.js"></script>
</html>
```

Perhaps this is a node/npm version issue? It does appear to be related to dependency resolution. Below is what I'm using.

> npm --version
> 3.3.9
> node --version
> v4.2.1

**Comment by knowbody** [comment] 2015-11-03 16:52
can you just try removing the whole thing and clone the repo once again and then, `npm install && npm start`? I'm not sure how to help you as this is not the issue with the project itself. Works for me on Mac, works for @brakmic on Windows. 

If I could reproduce it then I'd be happy to help.
