### ISSUE TITLE
npm start returns errors

### ISSUE THREAD

**Issue by egmanoj** [knowbody/redux-react-router-example-app#17] opened 2015-11-10 13:30 UTC
`npm start` yielded the following errors:

```
ERROR in ./src/javascript/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./views/Blog in /home/dockerdev/study/redux-react-router-example-app/src/javascript
 @ ./src/javascript/Root.js 53:17-40

ERROR in ./src/javascript/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./views/Draft in /home/dockerdev/study/redux-react-router-example-app/src/javascript
 @ ./src/javascript/Root.js 57:18-42

ERROR in ./src/javascript/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./views/Login in /home/dockerdev/study/redux-react-router-example-app/src/javascript
 @ ./src/javascript/Root.js 61:18-42
```

I'm using node `v4.2.1`

**Comment by knowbody** [comment] 2015-11-10 13:57
hmm, can you give some more info? Did you install all of the npm packages?

**Comment by egmanoj** [comment] 2015-11-10 14:15
I did execute `npm install`. I tried posting the contents of `npm ls -json` here but that's too long.

**Comment by egmanoj** [comment] 2015-11-10 14:42
Is there any specific module/configuration that I should look for?

**Comment by knowbody** [comment] 2015-11-10 14:47
good question, I don't know. Not sure why you are getting this errors. Hard to tell from the above stack trace...

**Comment by knowbody** [comment] 2015-11-11 15:46
any luck with that @egmanoj ?

**Comment by knowbody** [comment] 2015-11-14 13:19
closing as I can't reproduce it and as far as I know the project works fine for others. If it's a bug on my side I will reopen

**Closed as completed by knowbody** 2015-11-14 13:19 UTC

**Comment by ghost** [comment] 2016-03-18 21:02
I'm having the same issue, I can't tell myself what's wrong, sorry.
Running it on Ubuntu 14, the same errors.
using npm@3.3.12
using node@v5.2.0

```
$ webpack --display-error-details

Hash: 5d06a39db22f7bd21717
Version: webpack 1.12.14
Time: 3396ms
   [0] multi main 40 bytes {0} [built]
    + 828 hidden modules

ERROR in ./src/javascript/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./views/Blog in /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript
resolve file
  /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Blog is not a file
  /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Blog.js doesn't exist
resolve directory
  /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Blog/package.json doesn't exist (directory description file)
  directory default file index
    resolve file index in /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Blog
      /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Blog/index doesn't exist
      /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Blog/index.js doesn't exist
[/home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Blog.js]
[/home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Blog/index]
[/home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Blog/index.js]
 @ ./src/javascript/Root.js 55:17-40

ERROR in ./src/javascript/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./views/Draft in /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript
resolve file
  /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Draft is not a file
  /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Draft.js doesn't exist
resolve directory
  /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Draft/package.json doesn't exist (directory description file)
  directory default file index
    resolve file index in /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Draft
      /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Draft/index doesn't exist
      /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Draft/index.js doesn't exist
[/home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Draft.js]
[/home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Draft/index]
[/home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Draft/index.js]
 @ ./src/javascript/Root.js 59:18-42

ERROR in ./src/javascript/Root.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./views/Login in /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript
resolve file
  /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Login is not a file
  /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Login.js doesn't exist
resolve directory
  /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Login/package.json doesn't exist (directory description file)
  directory default file index
    resolve file index in /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Login
      /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Login/index doesn't exist
      /home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Login/index.js doesn't exist
[/home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Login.js]
[/home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Login/index]
[/home/mroutis/MEGA/Projects/MrOutis/redux-react-router-example-app/src/javascript/views/Login/index.js]
 @ ./src/javascript/Root.js 63:18-42
```

**Comment by knowbody** [comment] 2016-03-21 11:46
Thanks for reporting it. Really hard for me to track it, works fine for me. I will have a look into it once I have some more time. If you find out before please let me know.

**Comment by ghost** [comment] 2016-03-22 05:39
@knowbody, after trying again, I realized that the filename was `Index.js` instead of `index.js` (lowercase), I changed the indexes inside `./views/Login/` `./views/Draft/` and `./views/Blog/` and it worked. :beers: 

It would be cool to know if you have, somehow, a non-case-sensitive file system or something like that.

Here's more info: https://github.com/webpack/docs/wiki/resolving

**Comment by knowbody** [comment] 2016-03-22 14:03
@MrOutis thank you! good catch, mind sending the PR with those changes?
